local opts = vim.opt
opts.relativenumber = true
opts.mouse = a
opts.autoindent = true
opts.tabstop = 2
opts.shiftwidth = 2
opts.number = true
opts.termguicolors = true
opts.background = "dark"
opts.cursorline = true
opts.mouse = "a"
